<?php

namespace Fgms\ShopifyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MetaDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaDataRepository extends EntityRepository
{
}
