<?php

namespace Fgms\ShopifyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TabsMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabsMetaRepository extends EntityRepository
{
}
